media:
  - name: holz
    label: Holzbilder
    input: images/holz
    output: /images/holz

content:
  - name: holz
    label: Holz
    type: file
    path: content/holz.json
    format: json
    fields:
      - name: titel
        label: Titel
        type: string

      - name: slug
        label: Slug
        type: string

      - name: einleitung
        label: Einleitung
        type: text

      - name: galerie
        label: Galerie
        type: list
        fields:
          - name: bild
            label: Bild
            type: image
            media: holz

          - name: titel
            label: Bildtitel
            type: string

          - name: alt
            label: Alternativtext
            type: string
