media:
  - name: holz
    label: Holzbilder
    input: images/holz
    output: /images/holz
    rename: safe
    extensions: [jpg, jpeg, png, webp]

  - name: glas
    label: Glasbilder
    input: images/glas
    output: /images/glas
    rename: safe
    extensions: [jpg, jpeg, png, webp]

  - name: schiefer
    label: Schieferbilder
    input: images/schiefer
    output: /images/schiefer
    rename: safe
    extensions: [jpg, jpeg, png, webp]

  - name: zipper
    label: Zipperbilder
    input: images/zipper
    output: /images/zipper
    rename: safe
    extensions: [jpg, jpeg, png, webp]

  - name: edelstahl
    label: Edelstahlbilder
    input: images/edelstahl
    output: /images/edelstahl
    rename: safe
    extensions: [jpg, jpeg, png, webp]

  - name: leder
    label: Lederbilder
    input: images/leder
    output: /images/leder
    rename: safe
    extensions: [jpg, jpeg, png, webp]

  - name: keramik
    label: Keramikbilder
    input: /images/keramik
    output: /images/keramik
    rename: safe
    extensions: [jpg, jpeg, png, webp]


content:
  - name: holz
    label: Holz
    type: file
    path: content/holz.json
    format: json
    fields:
      - name: titel
        type: string
      - name: slug
        type: string
      - name: einleitung
        type: richtext
      - name: galerie
        label: Galerie
        type: object
        list: true
        fields:
          - name: bild
            label: Bild
            type: image
            media: holz
          - name: titel
            type: string
          - name: alt
            type: string


  - name: glas
    label: Glas
    type: file
    path: content/glas.json
    format: json
    fields:
      - name: titel
        type: string
      - name: slug
        type: string
      - name: einleitung
        type: richtext
      - name: galerie
        label: Galerie
        type: object
        list: true
        fields:
          - name: bild
            label: Bild
            type: image
            media: glas
          - name: titel
            type: string
          - name: alt
            type: string


  - name: schiefer
    label: Schiefer
    type: file
    path: content/schiefer.json
    format: json
    fields:
      - name: titel
        type: string
      - name: slug
        type: string
      - name: einleitung
        type: richtext
      - name: galerie
        label: Galerie
        type: object
        list: true
        fields:
          - name: bild
            label: Bild
            type: image
            media: schiefer
          - name: titel
            type: string
          - name: alt
            type: string


  - name: zipper
    label: Zipper
    type: file
    path: content/zipper.json
    format: json
    fields:
      - name: titel
        type: string
      - name: slug
        type: string
      - name: einleitung
        type: richtext
      - name: galerie
        label: Galerie
        type: object
        list: true
        fields:
          - name: bild
            label: Bild
            type: image
            media: zipper
          - name: titel
            type: string
          - name: alt
            type: string


  - name: edelstahl
    label: Edelstahl
    type: file
    path: content/edelstahl.json
    format: json
    fields:
      - name: titel
        type: string
      - name: slug
        type: string
      - name: einleitung
        type: richtext
      - name: galerie
        label: Galerie
        type: object
        list: true
        fields:
          - name: bild
            label: Bild
            type: image
            media: edelstahl
          - name: titel
            type: string
          - name: alt
            type: string


  - name: leder
    label: Leder
    type: file
    path: content/leder.json
    format: json
    fields:
      - name: titel
        type: string
      - name: slug
        type: string
      - name: einleitung
        type: richtext
      - name: galerie
        label: Galerie
        type: object
        list: true
        fields:
          - name: bild
            label: Bild
            type: image
            media: leder
          - name: titel
            type: string
          - name: alt
            type: string


  - name: keramik
    label: Keramik
    type: file
    path: content/keramik.json
    format: json
    fields:
      - name: titel
        type: string
      - name: slug
        type: string
      - name: einleitung
        type: richtext
      - name: galerie
        label: Galerie
        type: object
        list: true
        fields:
          - name: bild
            label: Bild
            type: image
            media: keramik
          - name: titel
            type: string
          - name: alt
            type: string


settings:
  content:
    merge: true
